application: oops-final
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|json))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|json))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest